### PR TITLE
proprietary-files.sh: Include odm ADSP modules

### PR DESCRIPTION
**Pull request by pjgowtham**
Newer realme devices are populating it here.

### CODE REVIEW

**Comment by TheMalachite** [comment]
> Newer realme devices are populating it here.

It was WIP tho

**Comment by pjgowtham** [comment]
Ah i see

**Comment by TheMalachite** [comment]
> Ah i see, any issues you faced after adding this ?

Some odm blobs are missing depending over the devices, mainly camera one

**Comment by ShivamCM** [comment]
I haven't built any ROM since 2019, appreciate the help xD

**Pull request merged**
